version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/bollettaelettrica.log
loggers:
  BollettaIrenParser:
    level: DEBUG
    handlers: [file]
    propagate: no
#  pdf_reader:
#    level: Debug
#    handlers: [file,console]
root:
  level: DEBUG
  handlers: [console,file]